### ISSUE TITLE
Entity Provider framework implementation

### ISSUE THREAD

**Issue by lubomirw** [3KeyCompany/CZERTAINLY#4]
To be able to automate the end-to-end certificate lifecycle, we need to implement `Entity Provider` framework.
The `Entity Provider` should be able to communicate with the entity (the user of the certificate) and perform required operations to work with the keys and certificate(s).

Currently, we have an "Entity" defined in the platform, that can be assigned to the certificate. However, this is now only for the record, because there is no real implementation behind it. This functionality needs to be replaced by flexible entity provider framework..

Entity Provider is the integration connector representing some particular Entity that needs to manage certificates and other related data in time. Entity is the owner of the private key and end user of the certificate. The Entity Provider should be able to work with different Entities through the implementation of the connector of different kind.

The Entity can then manage multiple certificate based in their location. For example, in case of the Linux server, based on different file system locations. On the other hand certificate can be associated (added) to different locations of different entities (providers). This way we can manage certificate from inventory in its all location where it is present and applied.

Tasklist:
- [x] 3KeyCompany/CZERTAINLY-Interfaces#48
- [x] 3KeyCompany/CZERTAINLY-Core#72
- [x] 3KeyCompany/CZERTAINLY-Core#73
- [x] 3KeyCompany/CZERTAINLY-Keystore-Entity-Provider#1
